server:
  port: 8087 # Port dédié au service de workflow

spring:
  application:
    name: workflow-service
  sql:
    init:
      mode: always

  # ===============================================
  # Base de données (pour stocker l'état des workflows)
  # ===============================================
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db # Assurez-vous que cette base de données existe
    username: postgres
    password: 1985
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# Configuration du client Eureka
# ===============================================
eureka:
  client:
    service-url:
      defaultZone: http://eureka-admin:pkf@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
jwt:
  secret: "VGhpcy1pcy1hLXN1cGVyLWxvbmcgYW5kLWNvbXBsZXgtc2VjcmV0LXN0cmluZy1lbmNvZGVkLWluLWJhc2U2NA"
  expiration-ms: 86400000