services:
  conventions-service:
    image: conventions-service
    build: .
    env_file: .env
    environment:
      - "8095:${PORT:-8095}"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

volumes:
  minio-storage:
      driver: local

