server:
  port: 8085

spring:
  application:
    name: messaging-service
  sql:
    init:
      mode: always

  # ===============================================
  # Configuration de la base de données PostgreSQL
  # ===============================================
  datasource:
    url: jdbc:postgresql://localhost:5432/messaging_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: postgres
    password: 1985
    driver-class-name: org.postgresql.Driver

  # ===============================================
  # Configuration de JPA et Hibernate
  # ===============================================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ===============================================
# Configuration du client Eureka
# ===============================================
eureka:
  client:
    service-url:
      defaultZone: http://eureka-admin:pkf@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# ===============================================
# Configuration de la Sécurité JWT
# ===============================================
jwt:
    secret: "hgsdfjksdhfkjshfkjshfkjshdfkjshdfkjshfkjshdfkjsh"

