server:
  port: 8081

spring:
  application:
    name: offers-service
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/offer_db
    username: postgres
    password: pkf
    driver-class-name: org.postgresql.Driver

  # Configuration JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # cache:
  #   type: redis

  # data:
  #   redis:
  #     host: localhost
  #     port: 6379

eureka:   # <-- bien au niveau racine
  client:
    service-url:
      defaultZone: http://eureka-admin:pkf@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

jwt:
  secret: "VGhpcy1pcy1hLXN1cGVyLWxvbmcgYW5kLWNvbXBsZXgtc2VjcmV0LXN0cmluZy1lbmNvZGVkLWluLWJhc2U2NA"
  expiration-ms: 864000000

management:
  endpoints:
    jmx:
      exposure:
        exclude: "*"
  jmx:
    enabled: false
